---

- name: jenkins password
  ansible.builtin.shell: usermod -aG docker jenkins

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - python3-pip
    state: latest
    update_cache: true

- name: Install python
  ansible.builtin.pip:
    name: python-jenkins >= 0.4.12

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/test.xml') }}"
    name: test
    password: admin
    url: http://localhost:8080
    user: admin

- name: Create a jenkins build using basic authentication
  community.general.jenkins_build:
    name: "test"
    state: present
    user: admin
    password: admin
    url: http://localhost:8080