---

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - python3-pip
    state: latest
    update_cache: true

- name: Install python
  ansible.builtin.pip:
    name: python-jenkins >= 0.4.12

- name: Install python
  ansible.builtin.pip:
    name: docker-py

- name: Build image using cache source
  community.docker.docker_image:
    name: testmaxdev/jenkins-image:v01
    build:
      path: /var/lib/jenkins/workspace/test/app
    source: build    

- name: Log into DockerHub
  community.docker.docker_login:
    username: testmaxdev
    password: zpfybvf.cmA!

- name: Tag and push to docker hub
  community.docker.docker_image:
    name: testmaxdev/jenkins-image
    repository: testmaxdev/jenkins-image
    tag: v01
    push: true
    source: local